import { defineConfig } from 'vitepress'

// Categories for all coding languages, courses, all in one
const languages = [
  { text: 'JavaScript', link: '/languages/javascript' },
  { text: 'TypeScript', link: '/languages/typescript' },
  { text: 'Python', link: '/languages/python' },
  { text: 'Java', link: '/languages/java' },
  { text: 'C', link: '/languages/c' },
  { text: 'C++', link: '/languages/cpp' },
  { text: 'C#', link: '/languages/csharp' },
  { text: 'Go', link: '/languages/go' },
  { text: 'Rust', link: '/languages/rust' },
  { text: 'PHP', link: '/languages/php' },
  { text: 'Ruby', link: '/languages/ruby' },
  { text: 'Swift', link: '/languages/swift' },
  { text: 'Kotlin', link: '/languages/kotlin' },
  { text: 'SQL', link: '/languages/sql' },
  { text: 'HTML / CSS', link: '/languages/html-css' },
  { text: 'Bash / Shell', link: '/languages/bash' },
  { text: 'Assembly', link: '/languages/assembly' },
]

const courses = [
  {
    text: 'Computer Science (OSSU)',
    link: '/courses/computer-science/',
    items: [
      { text: 'Intro CS — CS50', link: '/courses/computer-science/1-cs50-harvard' },
      { text: 'Core Programming', link: '/courses/computer-science/2-systematic-program-design' },
      { text: 'Object-Oriented Design', link: '/courses/computer-science/2-object-oriented-design' },
      { text: 'Discrete Math', link: '/courses/computer-science/3-discrete-math-mit-6-042j' },
      { text: 'Nand to Tetris', link: '/courses/computer-science/4-nand-to-tetris' },
      { text: 'Algorithms & Data Structures', link: '/courses/computer-science/5-algorithms-data-structures' },
      { text: 'Final Project', link: '/courses/computer-science/6-capstone' },
    ],
  },
  {
    text: 'Web Development',
    link: '/courses/web-development/',
    items: [
      { text: 'First HTML page', link: '/courses/web-development/1-your-first-html-page' },
      { text: 'Styling with CSS', link: '/courses/web-development/1-styling-with-css' },
      { text: 'Command Line & Git', link: '/courses/web-development/1-command-line-git' },
      { text: 'JavaScript Basics', link: '/courses/web-development/2-basics' },
      { text: 'DOM & Events', link: '/courses/web-development/2-dom-events' },
      { text: 'Fetch & APIs', link: '/courses/web-development/2-fetch-apis' },
      { text: 'REST API (Express)', link: '/courses/web-development/3-a-rest-api' },
      { text: 'SQL Schema', link: '/courses/web-development/4-schema-queries' },
      { text: 'Capstone', link: '/courses/web-development/5-ship-a-real-app' },
    ],
  },
  {
    text: 'Data Structures & Algorithms',
    link: '/courses/dsa/',
    items: [
      { text: 'Big-O', link: '/courses/dsa/1-big-o' },
      { text: 'Arrays & Strings', link: '/courses/dsa/2-arrays-strings' },
      { text: 'BFS & DFS', link: '/courses/dsa/3-bfs-dfs' },
      { text: 'Dynamic Programming', link: '/courses/dsa/4-memoization-tabulation' },
    ],
  },
  {
    text: 'Machine Learning',
    link: '/courses/machine-learning/',
    items: [
      { text: 'Python Syntax & Data', link: '/courses/machine-learning/1-syntax-data' },
      { text: 'Functions & Types', link: '/courses/machine-learning/1-functions-types' },
      { text: 'Linear Algebra', link: '/courses/machine-learning/2-linear-algebra' },
      { text: 'Supervised Learning', link: '/courses/machine-learning/3-supervised-learning' },
      { text: 'Neural Networks', link: '/courses/machine-learning/4-neural-networks' },
      { text: 'Transformers', link: '/courses/machine-learning/4-transformers' },
      { text: 'RAG & Agents', link: '/courses/machine-learning/5-rag-agents' },
    ],
  },
  {
    text: 'DevOps & Cloud',
    link: '/courses/devops/',
    items: [
      { text: 'The Shell', link: '/courses/devops/1-the-shell' },
      { text: 'Git', link: '/courses/devops/1-git' },
      { text: 'Docker', link: '/courses/devops/2-docker' },
      { text: 'CI/CD & K8s', link: '/courses/devops/3-github-actions-k8s' },
    ],
  },
  {
    text: 'Docker & Containers',
    link: '/courses/docker/',
    items: [
      { text: 'Install Docker', link: '/courses/docker/1-install-docker' },
      { text: 'The Docker Command Line', link: '/courses/docker/1-the-docker-command-line' },
      { text: 'Docker Contexts', link: '/courses/docker/1-docker-contexts' },
      { text: 'Pulling & Managing Images', link: '/courses/docker/2-pulling-managing-images' },
      { text: 'Running Containers', link: '/courses/docker/2-running-containers' },
      { text: 'Executing & Inspecting', link: '/courses/docker/2-executing-inspecting' },
      { text: 'Container Lifecycle & Cleaning', link: '/courses/docker/2-container-lifecycle-cleaning' },
      { text: 'Your First Dockerfile', link: '/courses/docker/3-your-first-dockerfile' },
      { text: 'All Dockerfile Instructions', link: '/courses/docker/3-all-dockerfile-instructions' },
      { text: 'CMD vs ENTRYPOINT', link: '/courses/docker/3-cmd-vs-entrypoint' },
      { text: 'Layers, Caching & .dockerignore', link: '/courses/docker/3-layers-caching-dockerignore' },
      { text: 'Multi-Stage Builds', link: '/courses/docker/3-multi-stage-builds' },
      { text: 'Optimizing Image Size', link: '/courses/docker/3-optimizing-image-size-reproducibility' },
      { text: 'Build Args, Targets & Cache', link: '/courses/docker/3-build-args-targets-cache' },
      { text: 'Volumes (Named)', link: '/courses/docker/4-volumes-named' },
      { text: 'Bind Mounts', link: '/courses/docker/4-bind-mounts' },
      { text: 'tmpfs Mounts', link: '/courses/docker/4-tmpfs-mounts' },
      { text: 'Backup & Restore a Volume', link: '/courses/docker/4-backup-restore-a-volume' },
      { text: 'Network Drivers', link: '/courses/docker/5-network-drivers' },
      { text: 'Bridge Networks & DNS', link: '/courses/docker/5-bridge-networks-dns' },
      { text: 'Port Mapping & Publishing', link: '/courses/docker/5-port-mapping-publishing' },
      { text: 'Container Networking Deep', link: '/courses/docker/5-container-networking-deep' },
      { text: 'Environment Variables', link: '/courses/docker/6-environment-variables' },
      { text: 'Secrets & Configs', link: '/courses/docker/6-secrets-configs' },
      { text: 'Logging & Monitoring', link: '/courses/docker/6-logging-monitoring' },
      { text: 'Compose Basics', link: '/courses/docker/7-compose-basics' },
      { text: 'Compose Spec Deep Dive', link: '/courses/docker/7-compose-spec-deep-dive' },
      { text: 'Multi-Environment Compose', link: '/courses/docker/7-multi-environment-compose' },
      { text: 'Pushing to Docker Hub', link: '/courses/docker/8-pushing-to-docker-hub' },
      { text: 'GitHub Container Registry (GHCR)', link: '/courses/docker/8-github-container-registry-ghcr' },
      { text: 'Private Registries & Mirror', link: '/courses/docker/8-private-registries-mirror' },
      { text: 'Running as Non-Root', link: '/courses/docker/9-running-as-non-root' },
      { text: 'Image Scanning (CVEs)', link: '/courses/docker/9-image-scanning-cves' },
      { text: 'Hardening Containers', link: '/courses/docker/9-hardening-containers' },
      { text: 'Signing Images (Notation)', link: '/courses/docker/9-signing-images-notation' },
      { text: 'CPU & Memory Limits', link: '/courses/docker/10-cpu-memory-limits' },
      { text: 'Restart Policies', link: '/courses/docker/10-restart-policies' },
      { text: 'Healthchecks', link: '/courses/docker/10-healthchecks' },
      { text: 'Docker Swarm Basics', link: '/courses/docker/11-docker-swarm-basics' },
      { text: 'Deploying to Cloud', link: '/courses/docker/11-deploying-to-cloud' },
      { text: 'CI/CD with GitHub Actions', link: '/courses/docker/11-ci-cd-with-github-actions' },
      { text: 'Debugging Containers', link: '/courses/docker/12-debugging-containers' },
      { text: 'Common Errors & Fixes', link: '/courses/docker/12-common-errors-fixes' },
      { text: 'Capstone — Ship a Production App', link: '/courses/docker/12-capstone-ship-a-production-app' },
    ],
  },
  {
    text: 'Kubernetes',
    link: '/courses/kubernetes/',
    items: [
      { text: 'What is Kubernetes?', link: '/courses/kubernetes/1-what-is-kubernetes' },
      { text: 'Install kubectl & a Cluster', link: '/courses/kubernetes/1-install-kubectl-a-cluster' },
      { text: 'kubectl Essentials', link: '/courses/kubernetes/1-kubectl-essentials' },
      { text: 'Your First Pod', link: '/courses/kubernetes/2-your-first-pod' },
      { text: 'Deployments', link: '/courses/kubernetes/2-deployments' },
      { text: 'Rolling Updates & Rollbacks', link: '/courses/kubernetes/2-rolling-updates-rollbacks' },
      { text: 'Jobs & CronJobs', link: '/courses/kubernetes/2-jobs-cronjobs' },
      { text: 'Service Types', link: '/courses/kubernetes/3-service-types' },
      { text: 'ClusterIP & DNS', link: '/courses/kubernetes/3-clusterip-dns' },
      { text: 'Ingress', link: '/courses/kubernetes/3-ingress' },
      { text: 'ConfigMaps', link: '/courses/kubernetes/4-configmaps' },
      { text: 'Secrets', link: '/courses/kubernetes/4-secrets' },
      { text: 'Volumes & PVCs', link: '/courses/kubernetes/4-volumes-persistentvolumeclaims' },
      { text: 'Probes (Liveness/Readiness)', link: '/courses/kubernetes/5-probes-liveness-readiness' },
      { text: 'Resource Requests & Limits', link: '/courses/kubernetes/5-resource-requests-limits' },
      { text: 'Horizontal Pod Autoscaler', link: '/courses/kubernetes/5-horizontal-pod-autoscaler' },
      { text: 'Namespaces & RBAC', link: '/courses/kubernetes/6-namespaces-rbac' },
      { text: 'Helm Basics', link: '/courses/kubernetes/6-helm-basics' },
      { text: 'GitOps with Argo CD', link: '/courses/kubernetes/6-gitops-with-argo-cd' },
      { text: 'Observability & Capstone', link: '/courses/kubernetes/6-observability-capstone' },
    ],
  },
  {
    text: 'Assembly Language',
    link: '/courses/assembly/',
    items: [
      { text: 'What is Assembly? & The CPU', link: '/courses/assembly/1-what-is-assembly' },
      { text: 'Toolchain', link: '/courses/assembly/2-toolchain' },
      { text: 'Registers & First Program', link: '/courses/assembly/3-first-program' },
      { text: 'Moving Data', link: '/courses/assembly/4-moving-data' },
      { text: 'Arithmetic & Logic', link: '/courses/assembly/5-arithmetic-logic' },
      { text: 'Control Flow', link: '/courses/assembly/6-control-flow' },
      { text: 'Stack & Functions', link: '/courses/assembly/7-stack-functions' },
      { text: 'Data & Strings', link: '/courses/assembly/8-data-strings' },
      { text: 'System Calls', link: '/courses/assembly/9-system-calls' },
      { text: 'Capstone', link: '/courses/assembly/10-capstone' },
    ],
  },
  {
    text: 'AWS Cloud',
    link: '/courses/aws/',
    items: [
      { text: 'Account, CLI & Free Tier', link: '/courses/aws/1-account-cli' },
      { text: 'IAM: Users, Groups, Roles', link: '/courses/aws/2-iam' },
      { text: 'EC2: First Virtual Server', link: '/courses/aws/3-ec2' },
      { text: 'S3: Object Storage', link: '/courses/aws/4-s3' },
      { text: 'VPC: Networking', link: '/courses/aws/5-vpc' },
      { text: 'RDS: Managed Databases', link: '/courses/aws/6-rds' },
      { text: 'Lambda: Serverless', link: '/courses/aws/7-lambda' },
      { text: 'Load Balancers & ASG', link: '/courses/aws/8-elb-asg' },
      { text: 'Security & Best Practices', link: '/courses/aws/9-security' },
      { text: 'Capstone: 3-Tier App', link: '/courses/aws/10-capstone' },
    ],
  },
  {
    text: 'Mobile Development',
    link: '/courses/mobile/',
    items: [
      { text: 'Android Screen & State', link: '/courses/mobile/1-first-screen-state' },
      { text: 'SwiftUI Counter', link: '/courses/mobile/2-swiftui-counter' },
      { text: 'Flutter Widgets', link: '/courses/mobile/3-widgets' },
      { text: 'Capstone', link: '/courses/mobile/4-ship-an-app' },
    ],
  },
  {
    text: 'Databases',
    link: '/courses/databases/',
    items: [
      { text: 'Schema & Normalization', link: '/courses/databases/1-schema-normalization' },
      { text: 'Joins & Window Functions', link: '/courses/databases/2-joins-window-functions' },
      { text: 'Indexing & Tuning', link: '/courses/databases/3-indexes-explain' },
    ],
  },
  {
    text: 'System Design',
    link: '/courses/system-design/',
    items: [
      { text: 'Metrics & Building Blocks', link: '/courses/system-design/1-metrics-building-blocks' },
      { text: 'Caching & Sharding', link: '/courses/system-design/2-caching-sharding' },
      { text: 'The Interview Framework', link: '/courses/system-design/3-design-interviews' },
      { text: 'Networking & DNS', link: '/courses/system-design/4-networking-dns' },
      { text: 'Load Balancing', link: '/courses/system-design/5-load-balancing' },
      { text: 'CDN & Edge', link: '/courses/system-design/6-cdn-edge' },
      { text: 'Databases & Replication', link: '/courses/system-design/7-databases-replication' },
      { text: 'Consistency & CAP', link: '/courses/system-design/8-consistency-cap' },
      { text: 'Caching Deep (Redis)', link: '/courses/system-design/9-caching-redis' },
      { text: 'Message Queues & Streams', link: '/courses/system-design/10-queues-streams' },
      { text: 'Microservices & APIs', link: '/courses/system-design/11-microservices-apis' },
      { text: 'Scaling & Sharding Deep', link: '/courses/system-design/12-scaling-sharding-deep' },
      { text: 'Rate Limiting & Resilience', link: '/courses/system-design/13-rate-limiting-resilience' },
      { text: 'End-to-End Designs', link: '/courses/system-design/14-end-to-end-designs' },
      { text: 'Estimation & Capacity', link: '/courses/system-design/15-estimation' },
    ],
  },
  {
    text: 'Cybersecurity',
    link: '/courses/cybersecurity/',
    items: [
      { text: 'CIA Triad & OWASP', link: '/courses/cybersecurity/1-cia-triad-owasp' },
      { text: 'XSS & SQL Injection', link: '/courses/cybersecurity/2-xss-sql-injection' },
      { text: 'OverTheWire CTF', link: '/courses/cybersecurity/3-overthewire' },
    ],
  },
]

export default defineConfig({
  title: 'DevNotes',
  description: 'All-in-one coding notes & courses documentation',
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: true,
  head: [
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', {
      rel: 'stylesheet',
      href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;600&display=swap',
    }],
    ['link', { rel: 'manifest', href: '/manifest.webmanifest' }],
    ['meta', { name: 'theme-color', content: '#4f46e5' }],
  ],
  markdown: {
    lineNumbers: true,
    theme: { light: 'github-light', dark: 'github-dark' },
  },
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Languages', link: '/languages/javascript' },
      { text: 'Courses', link: '/courses/web-development' },
      { text: 'Expert Standard', link: '/expert-standard' },
      { text: 'Resource Library', link: '/expert-resource-library' },
      { text: '🏷️ Tags', link: '/tags' },
      { text: '✏️ Editor', link: '/editor' },
      { text: '⚙️ ASM Playground', link: '/assembly-playground' },
      { text: '🖥️ Online Compiler', link: '/compiler' },
    ],
    sidebar: {
      '/languages/': [
        {
          text: 'Languages',
          items: languages,
        },
      ],
      '/courses/': courses,
      '/': [
        {
          text: 'Getting Started',
          items: [
            { text: 'Introduction', link: '/' },
            { text: 'How to Use', link: '/getting-started' },
            { text: 'Expert Knowledge Standard', link: '/expert-standard' },
            { text: 'Expert Resource Library', link: '/expert-resource-library' },
            { text: 'Expert Mastery Roadmap', link: '/expert-mastery-roadmap' },
            { text: '📊 Progress Dashboard', link: '/progress' },
          ],
        },
        {
          text: 'Languages',
          items: languages,
        },
        ...courses,
        {
          text: 'Tools',
          items: [
            { text: '🏷️ Browse by Tag', link: '/tags' },
            { text: '✏️ In-Browser Editor', link: '/editor' },
            { text: '🖥️ Online Compiler', link: '/compiler' },
          ],
        },
      ],
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com' },
    ],
    search: {
      provider: 'local',
    },
    footer: {
      message: 'Built with VitePress — edit & save your notes live.',
      copyright: '© ' + new Date().getFullYear() + ' DevNotes',
    },
  },
})
